better error handling

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,7 +5,12 @@ BUNDLES_DIR="$HOME/Library/Application Support/TextMate/Bundles"
 BUNDLE_SOURCE=$(cd $(dirname "$0") && pwd)
 BUNDLE_DEST="$BUNDLES_DIR/GitHub.tmbundle"
 
-ln -s -f "$BUNDLE_SOURCE" "$BUNDLE_DEST" || (echo "Error creating link" && exit 1)
-osascript -e 'tell app "TextMate" to reload bundles' || (echo "Error reloading bundles" && exit 1)
+function error(){
+	echo "`basename $0`: error: $1"
+	exit 1
+}
+
+ln -s -f "$BUNDLE_SOURCE" "$BUNDLE_DEST" || error "Error creating link"
+osascript -e 'tell app "TextMate" to reload bundles' || error "Error reloading bundles"
 
 echo "Done."
